name: FreeBSD
on:
  push:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - 'configure.ac'
      - 'Makefile.am'
      - '.github/workflows/FreeBSD.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - 'configure.ac'
      - 'Makefile.am'
      - '.github/workflows/FreeBSD.yml'



jobs:
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: vmactions/freebsd-vm@v1
      with:
        release: "15"
        cache-after-prepare: true
        prepare: |
          pkg install -y  automake autoconf libtool pkgconf libevent msgpack-c libssh
        usesh: true
        run: |
          autoupdate
          ./autogen.sh
          ./configure
          make
          make install



