name: MacOS
on:
  push:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - 'configure.ac'
      - 'Makefile.am'
      - '.github/workflows/MacOS.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.c'
      - '**.h'
      - 'compat/*'
      - 'configure.ac'
      - 'Makefile.am'
      - '.github/workflows/MacOS.yml'



jobs:
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - run: |
        brew install automake autoconf libtool pkg-config libevent msgpack libssh
        autoupdate
        ./autogen.sh
        ./configure
        make
        sudo make install




